import type { StashItem } from "@/types";

export const SEED_ITEMS: StashItem[] = [
  {
    id: "seed-1",
    title: "Alto Alps",
    url: "https://unsplash.com",
    description: "Mountain landscape photography reference for editorial work",
    collection: "Inspiration",
    type: "Image",
    tags: ["nature", "landscape"],
    coverUrl:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    addedAt: new Date("2025-01-15"),
    link: "",
  },
  {
    id: "seed-2",
    title: "Dark Arts #4",
    url: "https://unsplash.com",
    description: "High-contrast dark UI reference for upcoming redesign",
    collection: "Design",
    type: "Reference",
    tags: ["dark", "ui"],
    coverUrl:
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80",
    addedAt: new Date("2025-01-18"),
    link: "",
  },
  {
    id: "seed-3",
    title: "Color Burst",
    url: "https://unsplash.com",
    description: "Vibrant gradient exploration for brand palette",
    collection: "Inspiration",
    type: "Image",
    tags: ["color", "abstract"],
    coverUrl:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    addedAt: new Date("2025-01-22"),
    link: "",
  },
  {
    id: "seed-4",
    title: "Still Life 10",
    url: "https://unsplash.com",
    description: "Object composition study with dramatic lighting",
    collection: "Photography",
    type: "Image",
    tags: ["still life", "lighting"],
    coverUrl:
      "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=600&q=80",
    addedAt: new Date("2025-01-28"),
    link: "",
  },
  {
    id: "seed-5",
    title: "Atlas UI Kit",
    url: "https://figma.com",
    description: "Complete design system with 400+ components",
    collection: "Design",
    type: "Resource",
    tags: ["figma", "ui kit"],
    coverUrl:
      "https://images.unsplash.com/photo-1545235617-9465d2a55698?w=600&q=80",
    addedAt: new Date("2025-02-01"),
    link: "",
  },
  {
    id: "seed-6",
    title: "Dusk Palette",
    url: "https://coolors.co",
    description: "Warm earth tones with deep evening hues",
    collection: "Inspiration",
    type: "Color",
    tags: ["palette", "warm"],
    coverUrl:
      "https://images.unsplash.com/photo-1507908708918-778587c9e563?w=600&q=80",
    addedAt: new Date("2025-02-05"),
    link: "",
  },
  {
    id: "seed-7",
    title: "Brutalist Layouts",
    url: "https://brutalistwebsites.com",
    description: "Raw, unfiltered web design for editorial inspiration",
    collection: "Design",
    type: "Reference",
    tags: ["brutalism", "web"],
    coverUrl:
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80",
    addedAt: new Date("2025-02-08"),
    link: "",
  },
  {
    id: "seed-8",
    title: "Film Grain Vol.3",
    url: "https://unsplash.com",
    description: "High-resolution analog film textures for overlays",
    collection: "Textures",
    type: "Asset",
    tags: ["film", "grain", "texture"],
    coverUrl:
      "https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=600&q=80",
    addedAt: new Date("2025-02-10"),
    link: "",
  },
];

export const COLLECTIONS = [
  "Inspiration",
  "Design",
  "Photography",
  "Research",
  "Typography",
  "Motion",
  "Textures",
  "Code",
];
export const TYPES = [
  "Image",
  "Reference",
  "Resource",
  "Article",
  "Video",
  "Color",
  "Asset",
  "Link",
];
export const TAG_POOL = [
  "ui",
  "ux",
  "typography",
  "color",
  "motion",
  "web",
  "mobile",
  "print",
  "3d",
  "dark",
  "minimal",
  "editorial",
  "nature",
  "abstract",
  "figma",
  "code",
];
