import { IoBookmarksOutline } from "react-icons/io5";
import { IoBookmarks } from "react-icons/io5";
import { PiListBold } from "react-icons/pi";
import { IoGrid } from "react-icons/io5";
import { IoFilter } from "react-icons/io5";
import { MdKeyboardDoubleArrowRight } from "react-icons/md";
import { RiHomeFill } from "react-icons/ri";
import { RiHomeLine } from "react-icons/ri";
import { PiUploadSimple } from "react-icons/pi";
import { IoSearchSharp } from "react-icons/io5";
import { RiCloseFill } from "react-icons/ri";
import { FaCheck } from "react-icons/fa6";
import { GoBell } from "react-icons/go";
import { FaChevronDown } from "react-icons/fa6";

export { IoBookmarksOutline as IcBookmarks } from "react-icons/io5";
export { IoBookmarks as IcBookmarksFilled } from "react-icons/io5";
export { IoSettingsOutline as IcSettings } from "react-icons/io5";
export { MdAdd as IcAdd } from "react-icons/md";
export { PiListBold as IcList } from "react-icons/pi";
export { IoGrid as IcGrid } from "react-icons/io5";
export { IoFilter as IcFilter } from "react-icons/io5";
export { MdKeyboardDoubleArrowRight as IcChevRight } from "react-icons/md";
export { RiHomeFill as IcHome } from "react-icons/ri";
export { RiHomeLine as IcHomeline } from "react-icons/ri";
export { PiUploadSimple as IcUploads } from "react-icons/pi";
export { IoSearchSharp as IcSearch } from "react-icons/io5";
export { RiCloseFill as IcX } from "react-icons/ri";
export { FaCheck as IcCheck } from "react-icons/fa6";
export { GoBell as IcBell } from "react-icons/go";
export { FaChevronDown as IcChevDown } from "react-icons/fa6";
