import { IoBookmarksOutline } from "react-icons/io5";
import { IoBookmarks } from "react-icons/io5";
import { PiListBold } from "react-icons/pi";
import { IoGrid } from "react-icons/io5";
import { IoFilter } from "react-icons/io5";
import { MdKeyboardDoubleArrowRight } from "react-icons/md";
import { RiHomeFill } from "react-icons/ri";
import { RiHomeLine } from "react-icons/ri";
import { PiUploadSimple } from "react-icons/pi";
import { IoSearchSharp } from "react-icons/io5";
import { RiCloseFill } from "react-icons/ri";
import { FaCheck } from "react-icons/fa6";
import { FiBell } from "react-icons/fi";
import { FaChevronDown } from "react-icons/fa6";
// import { RiHome2Fill } from "react-icons/ri";
import { MdBookmarks } from "react-icons/md";
import { BiTransfer } from "react-icons/bi";
import { LuEyeClosed } from "react-icons/lu";
import { LuEye } from "react-icons/lu";
import { PiFolderOpen } from "react-icons/pi";
import { PiFolderOpenFill } from "react-icons/pi";
// import { GoLink } from "react-icons/go";
import { FiLink } from "react-icons/fi";
// import { CiVideoOn } from "react-icons/ci";
import { FiVideo } from "react-icons/fi";
// import { CiImageOn } from "react-icons/ci";
import { LuImage } from "react-icons/lu";
import { LuStickyNote } from "react-icons/lu";
import { BsDot } from "react-icons/bs";
import { CgFileDocument } from "react-icons/cg";
import { IoDocumentText } from "react-icons/io5";
// import { GoCalendar } from "react-icons/go";
import { FiCalendar } from "react-icons/fi";
import { TbFileUpload } from "react-icons/tb";
import { IoDocumentTextSharp } from "react-icons/io5";
import { PiLinkSimpleBold } from "react-icons/pi";
import { MdOutlineCalendarMonth } from "react-icons/md";
export { IoBookmarksOutline as IcBookmarks } from "react-icons/io5";
export { IoBookmarks as IcBookmarksFilled } from "react-icons/io5";
export { IoSettingsOutline as IcSettings } from "react-icons/io5";
export { MdAdd as IcAdd } from "react-icons/md";
export { PiListBold as IcList } from "react-icons/pi";
export { IoGrid as IcGrid } from "react-icons/io5";
export { IoFilter as IcFilter } from "react-icons/io5";
export { MdKeyboardDoubleArrowRight as IcChevRight } from "react-icons/md";
export { RiHomeFill as IcHome } from "react-icons/ri";
export { RiHomeLine as IcHomeline } from "react-icons/ri";
export { PiUploadSimple as IcUploads } from "react-icons/pi";
export { IoSearchSharp as IcSearch } from "react-icons/io5";
export { RiCloseFill as IcX } from "react-icons/ri";
export { FaCheck as IcCheck } from "react-icons/fa6";
export { FiBell as IcBell } from "react-icons/fi";
export { FaChevronDown as IcChevDown } from "react-icons/fa6";
export { RiHomeFill as IcHomeFilled } from "react-icons/ri";
export { BiTransfer as IcTransfer } from "react-icons/bi";
export { LuEyeClosed as IcEyeClosed } from "react-icons/lu";
export { LuEye as IcEyeOpened } from "react-icons/lu";
export { PiFolderOpen as IcFolderOpen } from "react-icons/pi";
export { PiFolderOpenFill as IcFolderFilledOpen } from "react-icons/pi";
export { FiLink as IcLink } from "react-icons/fi";
export { FiVideo as IcVideo } from "react-icons/fi";
export { LuImage as IcImage } from "react-icons/lu";
export { LuStickyNote as IcNote } from "react-icons/lu";
export { BsDot as IcDot } from "react-icons/bs";
export { CgFileDocument as IcDocs } from "react-icons/cg";
export { IoDocumentTextSharp as IcDoc } from "react-icons/io5";
export { FiCalendar as IcCalendar } from "react-icons/fi";
export { TbFileUpload as IcUpload } from "react-icons/tb";
export { PiLinkSimpleBold as IcUplinkfilled } from "react-icons/pi";
export { MdOutlineCalendarMonth as IcCal } from "react-icons/md";
