import { IoBookmarksOutline } from "react-icons/io5";
import { IoBookmarks } from "react-icons/io5";
import { PiListBold } from "react-icons/pi";
import { IoGrid } from "react-icons/io5";
import { IoFilter } from "react-icons/io5";
import { MdKeyboardDoubleArrowRight } from "react-icons/md";
import { RiHomeFill } from "react-icons/ri";
import { RiHomeLine } from "react-icons/ri";
import { PiUploadSimple } from "react-icons/pi";
import { IoSearchSharp } from "react-icons/io5";
import { RiCloseFill } from "react-icons/ri";
import { FaCheck } from "react-icons/fa6";
import { GoBell } from "react-icons/go";
import { FaChevronDown } from "react-icons/fa6";
// import { RiHome2Fill } from "react-icons/ri";
import { MdBookmarks } from "react-icons/md";
import { BiTransfer } from "react-icons/bi";
import { LuEyeClosed } from "react-icons/lu";
import { LuEye } from "react-icons/lu";
import { PiFolderOpen } from "react-icons/pi";
import { PiFolderOpenFill } from "react-icons/pi";
import { GoLink } from "react-icons/go";
import { CiVideoOn } from "react-icons/ci";
import { CiImageOn } from "react-icons/ci";
import { LuStickyNote } from "react-icons/lu";
import { BsDot } from "react-icons/bs";
import { CgFileDocument } from "react-icons/cg";
import { IoDocumentText } from "react-icons/io5";
import { GoCalendar } from "react-icons/go";

export { IoBookmarksOutline as IcBookmarks } from "react-icons/io5";
export { IoBookmarks as IcBookmarksFilled } from "react-icons/io5";
export { IoSettingsOutline as IcSettings } from "react-icons/io5";
export { MdAdd as IcAdd } from "react-icons/md";
export { PiListBold as IcList } from "react-icons/pi";
export { IoGrid as IcGrid } from "react-icons/io5";
export { IoFilter as IcFilter } from "react-icons/io5";
export { MdKeyboardDoubleArrowRight as IcChevRight } from "react-icons/md";
export { RiHomeFill as IcHome } from "react-icons/ri";
export { RiHomeLine as IcHomeline } from "react-icons/ri";
export { PiUploadSimple as IcUploads } from "react-icons/pi";
export { IoSearchSharp as IcSearch } from "react-icons/io5";
export { RiCloseFill as IcX } from "react-icons/ri";
export { FaCheck as IcCheck } from "react-icons/fa6";
export { GoBell as IcBell } from "react-icons/go";
export { FaChevronDown as IcChevDown } from "react-icons/fa6";
export { RiHomeFill as IcHomeFilled } from "react-icons/ri";
export { BiTransfer as IcTransfer } from "react-icons/bi";
export { LuEyeClosed as IcEyeClosed } from "react-icons/lu";
export { LuEye as IcEyeOpened } from "react-icons/lu";
export { PiFolderOpen as IcFolderOpen } from "react-icons/pi";
export { PiFolderOpenFill as IcFolderFilledOpen } from "react-icons/pi";
export { GoLink as IcLink } from "react-icons/go";
export { CiVideoOn as IcVideo } from "react-icons/ci";
export { CiImageOn as IcImage } from "react-icons/ci";
export { LuStickyNote as IcNote } from "react-icons/lu";
export { BsDot as IcDot } from "react-icons/bs";
export { CgFileDocument as IcDocs } from "react-icons/cg";
export { GoCalendar as IcCalendar } from "react-icons/go";
